export const gallery = {
  'Open Day':{
    '2019':[
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2019/OD_2019_1.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2019/OD_2019_2.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2019/OD_2019_3.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2019/OD_2019_4.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2019/OD_2019_4.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2019/OD_2019_5.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2019/OD_2019_6.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2019/OD_2019_7.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2019/OD_2019_8.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2019/OD_2019_9.jpg',
      'caption':""
    }
  ],
  '2020':[
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2020/OD_2020_1.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2020/OD_2020_2.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2020/OD_2020_3.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2020/OD_2020_4.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2020/OD_2020_5.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2020/OD_2020_6.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2020/OD_2020_7.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2020/OD_2020_8.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2020/OD_2020_9.jpg',
      'caption':""
    }
  ]},
'Freshers Day': {
  '2022':[
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_1.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_2.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_3.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_4.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_5.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_6.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_7.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_8.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_9.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_10.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_11.jpg',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_12.jpg',
      'caption':""
    }
  ]
}
}
