export const monsoonPageData=
    {
    '2017':{
      title: "Monsoon School on Urban Floods – 2017",
      details:"The Department of Civil Engineering, Indian Institute of Science (IISc), Bangalore had organized a one-week Monsoon School on “Urban Floods” during July 3 – 8, 2017, as one of the outreach activities in the research project entitled, Urban Flood Management in India: Technology Driven Solutions, sponsored by ITRA (Information Technology Research Academy), Ministry of Information and Technology, Government of India. The School comprised of lectures and tutorials by experts, covering topics of urban meteorology, urban hydrology, radar and remote sensing analysis of rain events, big data analysis for urban processes, engineering practices and post-flood responses. Group discussions were arranged to bring out the relevance of the state-of-the-art tools and methodologies for managing urban floods in Indian cities. The School targeted the practicing engineers and young researchers working with government or private bodies and educational institutes. Venue for the Lectures: GJ Hall, Dept of Civil EnggVenue for Tutorials: Conference Room/Computer Room, Dept of Civil EngOverview of the event: The event consisted of 39 participants across India and neighbouring countries (Bhutan and Nepal) joined the workshop. Prof. Dev Niyogi from Purdue University and Dr. Bhanu Neupane from UNESCO, Paris joined the workshop as resource persons. Indian speakers, Prof. D Nagesh Kumar, Prof. M Sekhar, Prof. MS Mohan Kumar, Prof. P. P. Mujumdar, Prof. V V Srinivas, Prof. Arpita Mondal, Prof. J Indu delivered lectures on different topics relating to urban floods.  The participants of the workshop came from different backgrounds. Young faculty members from different educational institutions; Scientists from CDAC; Officials from Nepal and Bhutan; Research Scholars and graduate students from different education institutes including IIT Hyderabad, IISc Bangalore joined the workshop. This versatile group of participants helped to develop a very dynamic learning process through the workshop.Each day of the workshop was divided into two sessions. In the morning sessions, lectures were conducted and in the afternoon sessions, tutorials, short assignments on the topics covered were given, group discussions were arranged etc. A visit to KSNDMC was organized on 7th July, 2017 in the afternoon session of the workshop. All the participants visited KSNDMC office where the officials described the functioning of flood early warning systems, telemetric rain gauges and other weather monitoring instruments to the participants.",

        imgsArray:[
          '../../assets/images/Monsoon School/Speakers2017.png',
          '../../assets/images/Monsoon School/Monsoon-School_2017_Group_photo.jpg',
          '../../assets/images/Monsoon School/KSNDMC-2017.jpg',
        ]
      },


    '2018':{
      title: "Monsoon School on Urban Floods – 2018",
      details:"The Department of Civil Engineering, Indian Institute of Science (IISc), Bangalore had organized a one-week Monsoon School on “Urban Floods” during 2-7 July, 2018, as one of the outreach activities in the research project entitled, Urban Flood Management in India: Technology Driven Solutions, sponsored by ITRA (Information Technology Research Academy), Ministry of Information and Technology, Government of India and United Nations Educational, Scientific and Cultural Organization (UNESCO). The School comprised of lectures and tutorials by experts, covering topics of urban meteorology, urban hydrology, radar and remote sensing analysis of rain events, monsoon and extreme precipitation dynamics, urban groundwater, engineering practices and post-flood responses. Group discussions were arranged to bring out the relevance of the state-of-the-art tools and methodologies for managing urban floods in Indian cities. The School targeted the practicing engineers and young researchers working with government or private bodies and educational institutes. Venue for the Lectures: GJ Hall, Dept of Civil Engg. Venue for Tutorials: Conference Room, Dept of Civil Engg. Overview of the event: The event consisted of 37 participants from India and neighbouring countries (Bhutan, Nepal and Sri Lanka). Prof. Dev Niyogi from Purdue University and Dr. Bhanu Neupane from UNESCO, Paris joined the workshop as resource persons. Indian speakers, Prof. D Nagesh Kumar, Prof. M Sekhar, Prof. MS Mohan Kumar, Prof. P P Mujumdar, Prof. V V Srinivas, Dr. J Indu, Dr. Subimal Ghosh and Dr. Chandra Rupa R delivered lectures on different topics relating to urban floods. The participants of the workshop came from different backgrounds. Young faculty members, research scholars and graduate students from different educational institutes; Scientists from KSNDMC, CSTEP and CSSRI – RRS, Lucknow; Officials from Bhutan, Nepal and Sri Lanka and practitioners from private organizations joined the workshop. This versatile group of participants helped to develop a very dynamic learning process through the workshop. Each day of the workshop was divided into two sessions. In the morning sessions, lectures were conducted and in the afternoon sessions, tutorials, short assignments on the topics covered were given, group discussions were arranged etc. A visit to KSNDMC was organized on 6th July, 2018 in the afternoon session of the workshop. All the participants visited KSNDMC office where the officials described the functioning of flood early warning systems, telemetric rain gauges and other weather monitoring instruments to the participants.",

      imgsArray:[
        '../../assets/images/Monsoon School/Speakers2018.jpg',
        '../../assets/images/Monsoon School/Monsoon-School_2018_Group_photo.jpg',
        '../../assets/images/Monsoon School/KSNDMC-2018.jpg',
      ]
      }
    ,

    '2019':{
      title: "Monsoon School on Urban Floods – 2019",
      details:"Interdisciplinary Center for Water Research (ICWaR), Indian Institute of Science (IISc), Bangalore in collaboration with Knowledge Societies Division UNESCO, Paris, organised a one-week Monsoon School on Urban Floods during 05 – 10 August, 2019. The School was supported by UNESCO and partially funded by the research project entitled, “Urban Flood Model for Bangalore“, sponsored by Department of Science & Technology (DST), Government of India. The School comprised of lectures and tutorials by experts, covering topics of urban meteorology, urban hydrology, radar and remote sensing analysis of rain events, monsoon and extreme precipitation dynamics, urban groundwater, engineering practices and post-flood responses. Group discussions were arranged to bring out the relevance of the state-of-the-art tools and methodologies for managing urban floods in Indian cities. The School targeted the practicing engineers and young researchers working with government or private bodies and educational institutes. Venue for the Lectures and Tutorials: Lecture Hall, Interdisciplinary Center for Water Research (ICWaR) Overview of the event: The event consisted of 39 participants from India and neighboring country Nepal. Prof. Dev Niyogi from Purdue University and Dr. Bhanu Neupane from UNESCO, Paris joined the workshop as resource persons. Indian speakers, Prof. D Nagesh Kumar, Prof. M Sekhar, Prof. MS Mohan Kumar, Prof. P P Mujumdar, Prof. V V Srinivas, Dr. J Indu and Dr. Subimal Ghosh delivered lectures on different topics related to urban floods. The participants of the workshop came from different backgrounds. Young faculty members, research scholars and graduate students from different educational institutes; Scientists researchers from Symbiosis Institute of Geo-informatics, various NITs and IITs, WRIDD and WRRDC, Government of Nepal, and practitioners from private organizations and freelancers joined the workshop. This versatile group of participants helped to develop a very dynamic learning process through the workshop. Each day of the workshop was divided into two sessions. In the morning sessions, lectures were conducted and in the afternoon sessions, tutorials, short assignments on the topics covered were given, group discussions were arranged etc. A visit to KSNDMC was organized on 9th August, 2019 in the afternoon session of the workshop. All the participants visited KSNDMC office where the officials described the functioning of flood early warning systems, telemetric rain gauges and other weather monitoring instruments to the participants.",

      imgsArray:[
        '../../assets/images/Monsoon School/Speakers2019.jpg',
        '../../assets/images/Monsoon School/Monsoon-School_2019_Group_photo.jpg',
        '../../assets/images/Monsoon School/KSNDMC-2019.jpg',
      ]
      }
    ,

      '2023':{
        title: "Monsoon School on Urban Floods – 2023",
        details:" The Interdisciplinary Centre for Water Research (ICWaR), Indian Institute of Science (IISc), Bangalore is organising a one-week Monsoon School on Urban Floods during 07 – 12 August, 2023, as one of the outreach activities in the research project entitled, “Urban Modelling : Development of Multi-sectorial Simulation Lab and Science-based Decision Support Framework to Address Urban Environment Issues”, sponsored by Ministry of Electronics and Information Technology (MeitY) and Department of Science and Technology (DST) under the National Supercomputing Mission (NSM) Government of India. The School is targeted at imparting training to young researchers, field engineers and decision makers in addressing the urban flood problems with the state-of-the-art science and technologies. The School will comprise of lectures and tutorials by experts, covering topics of urban meteorology, urban hydrology, radar and remote sensing analysis of rain events, AI and big data analytics for urban processes, engineering practices and post-flood responses. Group discussions will be arranged to bring out the relevance of the state-of-the-art tools and methodologies for managing urban floods in Indian cities. Research students, representatives from Govt. and Non-Govt. Organisations from various parts of India and neighbouring countries of Sri Lanka, Nepal and Bhutan have benefitted by the School, in the earlier years.",

        imgsArray:[
          '../../assets/images/Monsoon School/Brochure_Monsoon-School-2023_page.jpg',
        ]
        },
      }

//Monsoon button opens a modal with button for each year
//Each year defines a tab with addition tab for form
//Onclick opens monsoon school for that year
