export const seminars = [
  {
    'ICWaR Guest Seminar Series': [
      {
        'title':"High resolution remote sensing data in eco-agro-hydrology: opportunities in the context of the CNES/ISRO TRISHNA mission",
        'Name of the speaker':'Dr. Gilles Boulet',
        'Title of the Seminar':'High resolution remote sensing data in eco-agro-hydrology: opportunities in the context of the CNES/ISRO TRISHNA mission',
        'Date and Time':'27 July 2023 (Thursday), 4:00pm',
        'Online Platform':'MS Teams (link of the seminar)',
        'About the Speaker':'Dr. Gilles Boulet is an IRD Senior Scientist affiliated with the CESBIO lab in Toulouse (https://www.cesbio.cnrs.fr/) and currently deputed at the Indo-French Cell for Water Science at the Indian Institute of Science. He leads the Ecosystem Stress Group of the TRISHNA CNES/ISRO Thermal InfraRed mission proposal on the French side and is the PI of several research projects sponsored by the french space agency CNES as well as the french national funding body ANR to develop and evaluate evapotranspiration products based on remote sensing data. His interests lie in water fluxes and variables retrieval from TIR data, land surface modeling and Data Assimilation. He has more than 30 years of experience in field experiments and research developments designed for semi-arid water resources sustainable management and currently leads one of the two CESBIO research teams entitled “Modeling and remote sensing of land surface processes”. He is also the Secretary of the Remote Sensing commission of IAHS. ',
        'Abstract':' In his talk, he will address what and how land surface water variables and fluxes can be retrieved from high resolution remote sensing data with current and future platforms such as TRISHNA, SBG or LSTM. This will be put in perspective with key questions such as the sustainable management of water resources at local an regional scales and the fire and drought risk assessment. He will bring also some concrete elements on the TRISHNA evapotranspiration and water stress products definition and algorithms, as well as the current and future corresponding cal/val activities.'
      },
      {
        'title':"Microwave and VIR remote sensing for soil moisture and crop phenology using AI",
        'Name of the speaker':' Dr. Jasmeet Judge',
        'Title of the Seminar':'Microwave and VIR remote sensing for soil moisture and crop phenology using AI',
        'Date and Time':'08 June 2023 (Thursday), 4:00pm',
        'Online Platform':'MS Teams (link to the video of the seminar)',
        'About the Speaker':'Jasmeet Judge is a Professor in the Agricultural and Biological Engineering Department at the University of Florida, where she is also the Director of the Center for Remote Sensing. She received the Ph.D. degree in electrical engineering and atmospheric, oceanic, and space sciences from the University of Michigan. Her expertise includes microwave remote-sensing applications to terrestrial hydrology for agricultural regions; machine learning methods for spatio-temporal scaling and data-model fusion. She has led many field experiments with active and passive microwave sensors to develop/improve remote sensing, crop growth, hydrology, and AI algorithms. She has been awarded NASA Group Achievement Awards for interdisciplinary field campaigns. She has been active in advocating for the protection of the EM spectrum for passive scientific use from radiofrequency interference as the past Chair of the National Academe’s Committee on Radio Frequency. She is a Senior Member of the IEEE Geoscience and Remote Sensing Society, where for the past 2.5 decades she has served in many roles.',
        'Abstract':'Space-borne sensors provide global information for many valuable applications including agriculture and hydrology. New sensors and technological advances continue to improve spatial and temporal resolutions, further enhancing its value. This seminar will include two research projects conducted at the Center for Remote Sensing: the first, spatio-temporal scaling of microwave observations for soil moisture studies using AI. In this project, data-driven machine learning methods are used to merge data at microwave and other wavelengths to obtain high resolution soil moisture in agricultural regions. In the second project, remotely sensed VIR observations are integrated with physics-guided machine learning for estimating in-season crop phenology.'
      },
      {
        'title':"Recent results from investigating annual rainfall-runoff relationship changes during the Millennium Drought in south-eastern Australia",
        'Name of the speaker':'Dr. Murray Peel',
        'Title of the Seminar':'Recent results from investigating annual rainfall-runoff relationship changes during the Millennium Drought in south-eastern Australia',
        'Date and Time':'Monday, May 29, 2023, 11:00 A.M (IST)',
        'Online Platform':'MS Teams (link to the video of the seminar)',
        'About the Speaker':'Dr Murray Peel is a Senior Lecturer and ARC Future Fellow in the Department of Infrastructure Engineering at the University of Melbourne. He has a Ph.D. (Geography) and BSc (Hons) from the University of Melbourne. His research interests include catchment hydrology; hydro-climatology; understanding the drivers of interannual variability of annual precipitation and runoff around the world; understanding and modelling the hydrologic impacts of land use change; understanding and modelling the hydrologic impacts of climate change and the uncertainty around those projections; improving hydrologic modelling under changing conditions; and drawing hydro-climatology insights from palaeoclimatology information. His research and consulting activities have produced over 120 publications, including 86 articles in international journals and 9book chapters.',
        'Abstract':'The Millennium Drought in south-eastern Australia (1997-2009 ) was a 13-year extended dry period during which unusual catchment responses were observed. In just over half of the catchments investigated a statistically significant downward shift in long-term annual rainfall-runoff relationship was observed. In those shifted catchments, a given amount of rainfall resulted in less runoff than expected during the drought. Furthermore, later research demonstrated that many of the shifted catchments had not recovered several years after the drought ended and they were still producing less runoff than expected. Here I present a summary of recent results from our investigations into shifted rainfall-runoff relationships and modelling of runoff during the Millennium Drought. The Millennium Drought is an observed case study of a prolonged dry period, potentially indicative of future conditions in south-eastern Australia, which has significant implications for long-term streamflow behavior and modelling of climate change runoff projections.'
      },
      {
        'title':"How the land resonates with the atmosphere: a manifesto for complexity in land models",
        'Name of the speaker':'Dr. Eleanor Blyth',
        'Title of the Seminar':'How the land resonates with the atmosphere: a manifesto for complexity in land models',
        'Date and Time':'24 April 2023 (Monday), 4:00pm',
        'Online Platform':'MS Teams (link to the video of the seminar)',
        'About the Speaker':'With over 30 years of academic research and land-surface model development at the UK Centre for Ecology and Hydrology in Wallingford. Eleanor’s scientific expertise is the role of the land surface in climate, meteorology and hydrology, with specialist expertise in Evapotranspiration and Land-Atmosphere Interactions. She has a particular interest in the complex interactions of ecology and hydrology and the role of this interaction in regional carbon budgets of the region. She is known for developing understanding of the physics of land surface models. Especially, the 3 components of evapotranspiration: interception, transpiration and bare soil evaporation using observations and models and for innovative methods for evaluating Land-Atmosphere models.',
        'Abstract':'The land system responds to changes and drivers from the atmosphere in different ways around the planet. This is true of both the water and energy system as well as the carbon system. In this talk, we explore how this change can affect the weather and climate system and what that means in terms of how complex our models need to be.'
      },
      {
        'title':"Working at the limit: How thermodynamics shapes the Earth system",
        'Name of the speaker':'Dr. Axel Kleidon',
        'Title of the Seminar':'Working at the limit: How thermodynamics shapes the Earth system',
        'Date and Time':'30 March 2023 (Thursday), 4:00pm',
        'Online Platform':'MS Teams (link to the video of the seminar)',
        'About the Speaker':'Axel Kleidon studied physics and meteorology at the University of Hamburg and Purdue University, Indiana, USA. He received his doctorate in 1998 from the Max Planck Institute for Meteorology on the influence of deep-rooted vegetation on the climate system. He subsequently conducted research at Stanford University in California and at the University of Maryland. Since 2006, he has led the independent research group “Theory and Modeling of the Biosphere” at the Max Planck Institute for Biogeochemistry in Jena, Germany. His research interests range from the thermodynamics of the Earth system to the natural limits of renewable energy sources.',
        'Abstract':'Earth system processes perform work to maintain motion, cycles and metabolisms – an aspect that is not commonly considered.  In this talk I will show how thermodynamics plays a central role in the Earth system, determining how and how much work can be extracted from sunlight.  Work, in turn, is a major constraint on dynamics, from atmospheric motion to hydrologic cycling and the global biosphere.  I show that by maximizing work we can describe highly complex Earth system processes in a relatively simple way.  I use examples from the atmospheric circulation, hydrology and terrestrial ecosystems to illustrate this approach and its utility for Earth system science.'
      },
      {
        'title':"Food Safety Standard Authority India Rules and Regulations for Packaged Drinking water",
        'Name of the speaker':'Dr. Yashavanth Kumar GS',
        'Title of the Seminar':'Food Safety Standard Authority India Rules and Regulations for Packaged Drinking water',
        'Date and Time':'28 February 2023 (Tuesday), 4:00pm',
        'Online Platform':'MS Teams (link to the video of the seminar)',
        'About the Speaker':'Dr. Yashavanth Kumar G S is the Chief Chemist at the Central Chemical Lab, Bangalore. He is a passionate communicator on the Food Safety and Standard act and Food Adulteration Concepts. He has published more than 13 Research articles in reputed peer-reviewed journals and presented research papers in various national/international conference proceedings. He was awarded the Rajiv Gandhi National Fellowship (2009-13) from University Grant Commission (UGC), New Delhi. He has a Ph.D in Chemistry (2014) from Kuvempu University, and has collaborations with IISc Bangalore. His research interests are Nanotechnology, Solar Cells and Food Chemistry.',
        'Abstract':'Packaged drinking water is both a need and a necessity in a country like India where most of the freshwater resources have a high contamination levels. We all are aware of multiple brands providing packaged drinking water, but are they following some standards and what are they? In this talk the regulations on packaged drinking water by the Food Safety Standard Authority of India (FSSI) will be discussed. More specifically: What are FSSI rules and regulations, how it works.  Guidelines for packaged drinking water and what are the water quality parameters.  FSSAI amended certain conditions for packaged drinking water. What are they?'
      },
      {
        'title':"Contending with Uncertainty in Hydrologic Experiments Across Scales",
        'Name of the speaker':'Dr. Rao S. Govindaraju',
        'Title of the Seminar':'Contending with Uncertainty in Hydrologic Experiments Across Scales',
        'Date and Time':'19 January 2023 (Thursday), 4:00pm',
        'Online Platform':'MS Teams (link to the video of the seminar)',
        'About the Speaker':'Rao S. Govindaraju is the Bowen Engineering Head and the Christopher B. and Susan S. Burke Professor in the School of Civil Engineering at Purdue University. He earned his PhD in civil engineering from the University of California, Davis, in 1989. His primary areas of research include surface and subsurface hydrology, contaminant transport, watershed hydrology, and climatic influences. He is interested in developing algorithms for analyzing and learning from hydrologic data. He specializes in problems dealing with uncertainty and spatial variability. His research work has been supported by various agencies such as NSF, EPA, DOD, and DOE.  He has chaired national level committees, served on the editorial boards of several journals, and served as the President of American Institute of Hydrology (2017-2018).',
        'Abstract':'Hydrologic modeling efforts have to contend with several types of uncertainties. Measurement uncertainties exist because of errors in measurements of state variables, while structural uncertainties result from errors in the mathematical representation of hydrologic processes. Further, parametric uncertainties arise from both measurement and structural uncertainties, and because of limited information in the available data. Despite its ubiquitous nature, uncertainty quantification is not addressed often because of (i) lack of good algorithms, and (ii) inability to separate the various forms of uncertainty through calibration exercises. In this regard, Dr. Govindaraju will share some of his enduring research efforts that he has been pursuing in collaboration with students, and try to read the tea leaves as to where his future efforts will lead him in this journey.'
      },
      {
        'title':"Sharing your research for impact and engagement",
        'Name of the speaker':'Pallavi Eswara',
        'Title of the Seminar':'Sharing your research for impact and engagement',
        'Date and Time':'23 December 2022 (Friday), 4:00pm',
        'Online Platform':'MS Teams (link to the video of the seminar)',
        'About the Speaker':'Pallavi Eswara (she/her) is the Director, Postdoctoral Affairs at Boston University (BU), Boston, Massachusetts since June 2022. In this role she manages both the administrative and professional development aspects of postdoc training. Some of the programs she has created so far at BU have been around preparation for academic careers and grant writing. Prior to that she worked briefly at Northeastern University, Boston in Graduate Operations. Majority of her professional career was at the Pennsylvania State University where she was the founding staff member in 2007 of the Office of Postdoctoral Affairs (OPA) and led the office as the Director from 2016-21.During the 14 years of her tenure in OPA, Pallavi created and established the annual postdoc research exhibition where postdocs from different disciplines shared their research with faculty, postdocs, graduate students from all disciplines, scientists and nonscientists. She also created a Science Cafe program where postdocs would share their research to lay audiences at a local coffee and community center. Additionally, she created a science outreach grant program to allow postdocs to create activities for local area school children. She has been invited to present on topics of professional development to both graduate students and postdocs. She has served in leadership roles in her community and in professional societies such as the National Postdoc Association and Graduate Career Consortium (GCC). Pallavi currently serves on the Executive Committee of GCC. Further details of her work and past scientific contributions are at https://www.linkedin.com/in/pallavi-eswara-86b59a11/',
        'Abstract':'There is an increasing need to engage with broad audiences to convey the findings, importance of scientific research and motivate younger generations to be involved with science. Academic and research institutions, funding bodies and government agencies are very interested in scientists being able to engage widely with the public. When it comes to sharing about their research to a broad audience- be it educated people, lay audience or school children it is indeed a challenge for scientists to convey the hypothesis, methods, findings and conclusions without technical jargon or feeling like they are “diluting the science”. In this talk, we will discuss the state of science communication, principles and best practices for communication to a broad audience. Benefits of this kind of engagement to the scientist and society will also be presented. The presentation will also discuss how scientists can use science communication as a tool to further interdisciplinary research collaboration and non-traditional stakeholder collaborations.'
      },
      {
        'title':"Water Systems Integration Modelling Framework – A Tool to Inform Future Water Planning at a Systems Level",
        'Name of the speaker':'Dr. Ana Mijic',
        'Title of the Seminar':'Water Systems Integration Modelling Framework – A Tool to Inform Future Water Planning at a Systems Level',
        'Date and Time':'30 November 2022 (Friday), 4:00pm',
        'Online Platform':'MS Teams (link to the video of the seminar)',
        'About the Speaker':'Dr Ana Mijic is a Reader in Water Systems Integration and Director of the Centre for Systems Engineering and Innovation (CSEI) at Imperial College London. She is leading the development of novel systems tools focused on quantifying the interaction between water systems and sustainable development. The work has aim to inform regulatory bodies and water industry if and how we can support economic growth whilst ensuring sustainable water use and flood and water quality management under future uncertainties. Through NERC Innovation Fellowship funding she worked with the UK Environment Agency to apply systems thinking and systemic approaches to develop principles of systems water management at a catchment scale. She has led the CHANSE project on systems water management and irrigation water use in India. Currently, Ana is a Systems Lead for the CAMELLIA impact programme, where her work is focused on the development of systems water management models and she is leading the VENTURA project, which is developing virtual decision rooms for water neutral urban planning. Ana is a member of the EWRE Hydrology group that was awarded the 2019 Imperial President’s Award for Excellence in Research for Outstanding Research Team and she is the recipient of 2022 Satish Dhawan Chair Professorship at IISc Bangalore.',
        'Abstract':'Integrated water management and planning has been a focus of research for many decades, but only recently we have started discussing the challenge from a systems perspective. The need for systems approach to water management is defined through integration between physical, environmental, and socio-economic components of the system, for which the evidence should be provided at adequate spatiotemporal resolutions. In this seminar, the novel Water Systems Integration Modelling (WSIMOD) Framework will be presented. The WISMOD allows for the representation of the water system’s demands and impacts of multiple sectors and actors’ decisions within a single tool, which is considered beneficial to increasing a shared understanding of system performance and for more collaborative and coherent decisions on integrated water resources, water quality and flood management. The WSIMOD is a self-contained software package that includes modelled representations of key physical and infrastructure elements of the water cycle (urban and rural), with each type of modelled element generically described as a component. Components are written in such a way that any component can interact with any other component. This enables a flexible representation of a water system that is needed to accommodate the wide variety of different built/natural infrastructure configurations and scales. The talk will showcase how the tool has been developed and successfully tested through a range of applications in the UK, including integrated analysis of urban water systems, catchment water management and urban water neutrality.'
      },
      {
        'title':"Shaping the Future of India’s Food Water Energy Livelihood Nexus",
        'Name of the speaker':'Dr. Naresh Devineni',
        'Title of the Seminar':'Shaping the Future of India’s Food Water Energy Livelihood Nexus',
        'Date and Time':'28 October 2022 (Friday), 9:00am',
        'Online Platform':'MS Teams (link to the video of the seminar)',
        'About the Speaker':'Naresh Devineni is an Associate Professor in the Department of Civil Engineering at The City University of New York’s City College. He holds an M.S. and Ph.D. in Civil Engineering from North Carolina State University. He did his post-doctoral studies at Columbia University. He also worked as a Consultant for the World Bank for a brief period in 2009. He is a past recipient of the U.S. Department of Energy’s Early Career Award. He has diverse interests in hydro-climate modeling and extremes analysis, statistical methods, water sustainability and risk assessment, and water systems analysis. His recent work focuses on agricultural systems sustainability in a changing climate, applied to the United States and the Indian subcontinent. More information about his research and professional activities can be found at https://nareshdevineni.com/about/',
        'Abstract':'This study provides a formal analysis of the design of an Indian food procurement system that considers climate-driven variations in renewable water supply, needs for groundwater pumping, varying regional productivity of crops, and farm-level economics, assuming that the food security goals are to be met while keeping current procurement prices fixed for each crop and maximizing net aggregate farm income from the procurement system. A systems approach is taken to integrate data from disparate sources and predict water stress and sustainable agricultural enhancement regions. A by-product of the analysis is a reduction in the aggregate use of non-renewable water and the consequent decrease in irrigation water requirements and hence water and energy stress. Thus, the “climate-food-water-energy-livelihood” nexus of issues is addressed conjunctively by leveraging data analytics and systems approaches. The talk will be based on our recent paper in Nature Communications on solving groundwater depletion in India while achieving food security https://www.nature.com/articles/s41467-022-31122-9'
      },
      {
        'title':"Effects of Urbanization and Extreme Climatic Events on Water Quantity and Quality",
        'Name of the speaker':'Dr. Tushar Sinha',
        'Title of the Seminar':'Effects of Urbanization and Extreme Climatic Events on Water Quantity and Quality',
        'Date and Time':'28 September 2022 (Wednesday), 9:30pm',
        'Online Platform':'MS Teams (link to the video of the seminar)',
        'About the Speaker':' Dr. Sinha is working as an Associate Professor in the Department of Environmental Engineering at Texas A&M University – Kingsville (TAMUK). Prior to joining TAMUK in September 2014, he has worked as a Research Assistant Professor at North Carolina State University (NCSU) for over 1.5 years and as a Postdoctoral Scientist for about 4 years at NSCU and Arizona State University combined. He received his B.S. in Agricultural Engineering and MS in Civil Engineering from India and Ph.D. in Agriculture and Biological Engineering from Purdue University in 2008. He has worked in hydrologic modelling, climate change impacts on hydrology; water resources management; surface water – groundwater interactions; and geospatial analysis. He has published about 30 journal articles including several high impact journals such as PNAS, Earth’s Future and Journal of Geophysical Research. Dr. Sinha has received funding as PI and Co-PI from multiple federal and state agencies. He has also served as chair of technical sessions at national and international conferences. He has been a recipient of TAMU-K’s College of Engineering Excellence in Research Award in 2018.',
        'Abstract':'Rapid urbanization and intensification of extreme climatic events directly affect peak flow and water quality in streams in both urban and mixed-use watersheds. Low Impact Development (LID) strategies such as Green Roof (GR) and Rain Garden (RG) can partially mitigate such effects on stormwater runoff and water quality. However, efficiency of LID strategies in handling moderate to large rainfall events to improve the water quality of a watershed is not well understood. Thus, this talk will discuss how different LID strategies affect peak flow and water quality in urban and mixed-use watersheds. The analysis on effects of different LID strategies showed that during the high rainfall intensity event of 15 cm/day, no significant differences due to LID strategies were observed on the peak flow reduction. However, about 32% reduction in peak flow was attained when all three LID strategies considered in this study (GR, RG and GR+RG in series) under low to moderate rainfall intensities of 2 – 3 cm/day. In addition, better water management strategies are needed to mitigate floods and droughts by co-managing green (wetlands) and grey (dams) infrastructure. A framework to co-manage green and grey infrastructure will be discussed to enhance water resilience under extreme climatic events.'
      },
      {
        'title':"VEDAS: A platform for web-based visualization and analysis of Satellite data",
        'Name of the speaker':'Dr. Shashikant A Sharma',
        'Title of the Seminar':'VEDAS: A platform for web-based visualization and analysis of Satellite data',
        'Date and Time':'30 August 2022 (Tuesday), 4:00pm',
        'Online Platform':'MS Teams (link to the video of the seminar)',
        'About the Speaker':' Shashikant A Sharma, Scientist-G and Group Director, VEDAS Research Group, Space Applications Centre (ISRO), Ahmedabad, India. He joined ISRO in 1986 and has worked in the field of Remote Sensing, GIS, and Digital Image Processing. He has a special interest in applications of Geoinformatics for Agriculture and Renewable Energy. He is instrumental in the development of the Geospatial portal – VEDAS ( Visualisation of Earth Observation Data and Archival System) (https://vedas .sac.gov.in), which has visualization and analysis capabilities of Geospatial data. Earlier he was a lead role in the development of indigenous GIS software. His current interests are Digital Image Processing, Geospatial analytics on the Web, and AI/ML applications of Satellite data. He is the recipient of many national awards in the field of Geoinformatics.',
        'Abstract':'ISRO is operating a fleet of Earth Observation satellites with a wide range of sensors of varying capabilities. In addition to making satellites and launch vehicles, ISRO is also conducting scientific research and demonstrating applications of space-based inputs in many disciplines including agriculture, forestry, geology, environmental studies, urban planning, infrastructure development, meteorology, planetary sciences, disaster management, etc. The efficient utilization of this voluminous geospatial content generated by the thematic experts and the data acquired by several Indian and publicly available EO satellites is essential for adding greater societal value as envisaged by Dr Vikram Sarabhai, the founder of India’s space programme. In this context, the Space Applications Centre at Ahmedabad contemplated the development of the ‘Visualization of EO Data and Archival System’, abbreviated as VEDAS. It aims to organize the vast quantum of geospatial databases on various themes and develop customized decision support systems and applications for an improved understanding of the earth and planetary systems. VEDAS is a step towards creating a “geo-data-rich society” supporting mainstreaming of satellite imagery and remote sensing in the process of National Development. In this talk, I will provide an overview of the VEDAS, its capabilities and its potential for research and decision-making, while illuminating what lies ahead for us. For example, VEDAS has endeavoured to support web-based geospatial analysis by providing processing tools for analysis on the internet and we are now building an online interactive platform for Big Data analytics and supporting the application of Artificial Intelligence and Machine Learning (AI/ML) tools.'
      },
      {
        'title':"What (NOT) to do as an early career academic and researcher in India",
        'Name of the speaker':'Dr. Arpita Mondal',
        'Title of the Seminar':'What (NOT) to do as an early career academic and researcher in India',
        'Date and Time':'29 July 2022 (Friday), 4:00pm',
        'Online Platform':'MS Teams (link to the video of the seminar)',
        'About the Speaker':'Dr. Arpita Mondal works as an Associate Professor in the Department of Civil Engineering and Interdisciplinary Program in Climate Studies at the Indian Institute of Technology (IIT) Bombay. Her research focuses on hydroclimatic extremes – how they can be characterized, what causes them, and how they are likely to evolve with climate change. Arpita serves as an Associate Editor of the AGU journal Earth’s Future and the Springer journal Regional Environmental Change. She received the Early Career Research Award from the Science and Education Research Board (SERB), and the INSPIRE Faculty Award. She also received the Asian University Alliance (AUA) Scholars’ Award. Arpita has been selected to feature in the book ‘She Is: 75 Indian Women in STEAM’ by the Office of the Principal Scientific Advisor to the Government of India and the Red Dot Foundation, honoring 75 Indian Women in the fields of Science, Technology, Engineering, Arts and Mathematics. She has been an invited speaker in the session on Women in STEM in the South Asia Leadership Summit of the British Council, India. Arpita completed her PhD in Civil Engineering at the Indian Institute of Science (IISc), Bangalore, MTech in Water Resources Engineering at the Indian Institute of Technology Bombay and Bachelors in Civil Engineering at Jadavpur University, Kolkata. As a PhD student, Arpita had received the Endeavour Research Fellowship of the Government of Australia, the Fulbright-Nehru Research Fellowship of the United-States India Education Forum, and the Berkner Travel Grant of the American Geophysical Union (AGU).',
        'Abstract':'‘How to become a professor in an Indian Institute of Technology (IIT)?’ is a question which is asked by several in our country. There is an increasingly large number of awareness and mentoring programs conducted by organizations and academies in this country to address this query among the public in general, and graduate students in particular. Another equally important question to which answers must be sought is, ‘How to survive as an early career academic or researcher in today’s India?’. Many Indian academic or research institutions offer to young professionals what are termed as ‘permanent’ jobs; however, stagnation, dearth of progress and lack of navigation along multiple directions of growth (both one’s own individual growth and that of his/her employer) can prove fatal for one’s career and more importantly, personal well-being, if adequate, timely steps are not taken to make sure one is not only ‘surviving’ but also ‘thriving’, particularly compared to global benchmarks. In this seminar, I will talk about key responsibilities expected out of an early career academic in a leading engineering institute in India, highlight some opportunities and challenges towards a bright and successful academic/research career and also offer suggestions to avoid some mistakes (I think) I did. I will share some stories, and advice that I had been lucky to receive, and hopefully hear back from the audience about what drives them towards their own pursuit of excellence. Women graduate students and early career researchers are expected to particularly benefit from this talk, since I will also share some experiences and suggestions on overcoming gender-defined obstructions.'
      },
      {
        'title':"How microbes melt glaciers and ice sheets?",
        'Name of the speaker':'Prof. Alexandre Anesio',
        'Title of the Seminar':'How microbes melt glaciers and ice sheets?',
        'Date and Time':'30 June 2022 (Thursday), 4:00pm',
        'Online Platform':'MS Teams (link to the video of the seminar)',
        'About the Speaker':'Alexandre Anesio is a Professor in Arctic Microbiology in the Department of Environmental Science at Aarhus University. His main research interest is on microbial and biogeochemical processes in glaciers and ice sheets. He is currently one of the PIs in a European Research Council Synergy grant to investigate how pigmented algae, growing directly on the snow and bare ice, through their photophysiology, have a crucial role in changing the reflectivity of the ice (i.e., albedo), and subsequently the melt rates of the ice. Anesio obtained his PhD degree at Lund University in Sweden in 2000, where he also worked as postdoc until 2003. Since then, he has worked at the University of Nottingham (2003-2004), Aberystwyth University (2004-2007) and University of Bristol (2007-2018), until moving to Denmark in 2018.',
        'Abstract':'Glaciers and ice sheets were long believed to be sterile environments, but just like other large ecosystems (e.g., tropical forests, tundra), they are now widely recognized as one of the Earth’s biomes, teeming with life. This biome is also the most under-investigated on the planet from a biological and biogeochemical perspective, representing a new and exciting frontier in science. Home to large, naturally occurring communities of mostly microbes, glaciers and ice sheets host metabolically active organisms, interacting with each other. These processes represent more than just a minor curiosity of life under extreme conditions. On glacier and ice sheet surfaces, microbes have been shown to alter physical and chemical characteristics of snow and ice with direct consequences for snow/ice solar-heating and amplified melt. During the summer ablation, the bare ice is largely dark, as it is colonized by pigmented ice algae. Biological growth of icebound algal cells can accumulate biomass high enough to cause albedo reduction between 12% and 21%, depending on the algal cell abundances. The impact of microbially-mediated albedo effect is predicted to increase further with climate change, since a warming climate will further extend melt seasons. Furthermore, microbial activity and carbon fixation on ice surfaces can result in export of labile dissolved organic matter to downstream ecosystems.'
      },
      {
        'title':"Representing Cities in Weather and Climate Models: From Processes to Urban Digital Twins",
        'Name of the speaker':'Prof. Dev Niyogi',
        'Title of the Seminar':'Representing Cities in Weather and Climate Models: From Processes to Urban Digital Twins',
        'Date and Time':'31 May 2022 (Tuesday), 4:00pm',
        'Online Platform':'MS Teams (link to the video of the seminar)',
        'About the Speaker':' Dr. DEV NIYOGI, is John E. “Brick” Elliot Centennial Endowed Professor at the University of Texas at Austin, in the Jackson School of Geosciences, and the Department of Civil, Architectural and Environmental Engineering. He is a graduate faculty of the Oden Institute of Computational Engineering and Science, and University of Texas Center for Space Research. He is also Professor Emeritus, Purdue University, Department of Agronomy and Department of Earth, Atmospheric, and Planetary Sciences, and former Indiana State Climatologist (2005- 2018). He is an Editor for the AMS Journal of Applied Meteorology and Climatology. Linkdn: https://www.linkedin.com/in/texus/   Prof. Niyogi’s research seeks to significantly contribute to our understanding of the Earth system, particularly the urban and agricultural landscapes, and the dynamic role of coupled land surface processes on weather and regional meteorological extremes. An important ongoing and emerging focus of his research is to translate the scientific work undertaken into decision tools and portals with a particular focus on hydroclimatology and sustainable climate-ready/resilient cities.',
        'Abstract':'Urbanization is a global phenomenon and a notable feature of anthropogenic impacts. Cities have a relatively small spatial footprint, but likely have a much larger and discernable impact on the regional weather, and hydroclimatic processes. This presentation is aimed as a primer to highlight what the science community has understood about the effects of cities and urban clusters on local to larger scale meteorological processes. The talk will draw on multiscale evidence from different studies to highlight the need for representing urban processes within weather and climate studies. The talk will also discuss different approaches underway in the traditional modeling sense involving physics-based framework, and the recent opportunities using AI/ML approaches culminating in the efforts underway for developing an urban digital twin.'
      },

      {
        'title':"Interaction of groundwater with surface water: the example of Ganges river",
        'Name of the speaker':'Prof. Abhijit Mukherjee',
        'Title of the Seminar':'Interaction of groundwater with surface water: the example of Ganges river',
        'Date and Time':'28 April 2022 (Thursday), 4:00pm',
        'Online Platform':'MS Teams [link to  the video of the seminar]',
        'About the Speaker':'Prof. Abhijit Mukherjee, PhD (Hydrogeology) graduated from the University of Kentucky, USA (2006) and completed postdoctoral work at the University of Texas at Austin, USA (2006-2008). He served as the Physical Hydrogeologist at the Alberta Geological Survey in Canada (2008-2010). He is currently an Associate Professor at the Department of Geology and Geophysics, and School of Environmental Science and Engineering at the Indian Institute of Technology Kharagpur (IIT Kharagpur), India. His main research areas are physical, chemical and isotope hydrogeology, including numerical modeling, computation, contaminant transport, water policy applications. He is known for his studies on geological and human-sourced groundwater pollution (e.g. arsenic, fluoride, sanitation-borne and emerging contaminants) in more than a dozen countries, water quantity estimates including application of advanced computation and Artificial Intelligence techniques. For his work on groundwater Prof. Mukherjee has been conferred the National Geoscience Award 2014 by the President of India, Kharaka Award in 2020 by International Association of Geochemist, inducted as Fellow to Royal Society of Chemistry (2020) and the Geological Society of America (2021), named as top 75 leading Scientists and Experts who are under 50 years of age. As the first South Asian, ever, he is presently serving in the Council of the Geological Society of America. He was awarded the Shanti Swarup Bhatnagar Prize in 2020, regarded as India’s highest science award.',
        'Abstract':'The mega-Himalayan river Ganges (or Ganga), one of the largest in the world and the lifeline of northern India for the last several thousand years, hosting almost 10% of the present global and half of Indian population on its fertile banks, has been found to have unprecedented low levels of river water (drying up) in several lower reaches in the summers of recent years. Using a combination of satellite-based and in-situ measurements of river water and groundwater levels, isotopic and chemical analyses of Ganges river and groundwater, simulation results from global hydrologic models and regional groundwater flow models, shows that the present-day summer drying of the river Ganges is possibly driven by groundwater depletion in the Gangetic aquifers of north India. One hypothesis is that a decrease in groundwater inflow (baseflow) has a severe impact on the health of the river. The present-day baseflow to the Ganges from the adjoining aquifers, which may be up to a third of total river volume during pre-monsoon months, might have decreased by >50% from the beginning of irrigation-pumping age in the 1970s. Under several assumptions and approximations, it has been predicted that the groundwater contribution to Ganges river water flow would continue to decrease in impending years, and can decrease up to ~75% of the 1970s. Thus, a continuation of the groundwater exploitation at similar per-capita rates might jeopardize the existence of the Ganges River in several reaches in near future, thereby leading to disastrous carbohydrate and other food scarcity for ~ 115 million people inhabiting in the study region by 2050.'
      },
      {
        'title':"Major findings from IPCC Water Chapter on Water Related Adaptations and their Effectiveness in reducing risks",
        'Name of the speaker':'Dr. Aditi Mukherji',
        'Title of the Seminar':'Major findings from IPCC Water Chapter on Water Related Adaptations and their Effectiveness in reducing risks',
        'Date and Time':'28 March 2022 (Monday), 4:00pm',
        'Online Platform':'MS Teams [link to  the video of the seminar]',
        'About the Speaker':'Dr. Aditi Mukherji is a Principal Researcher and leads the Research Group on Climate Change Adaptation and Resilience (CCAR) at the International Water Management Institute. Before this, she led the Water and Air Theme at the International Centre for Integrated Mountain Development (ICIMOD) in Nepal. She has over 20 years of experience working on policies and institutions of water resources management with a special focus on water-energy-food nexus. Her areas of specialization are groundwater governance, energy-irrigation nexus, climate change adaptation and community management of water resources.  She has worked in South Asia including the Hindu Kush Himalayan region, Nile basin and in Central Asia. She is currently a part of the 6th Assessment Report (AR6) team of the Intergovernmental Panel on Climate Change (IPCC) and is the Coordinating Lead Author (CLA) of the Water Chapter in the Working Group II on Adaptation and Vulnerability and a member of Core Writing Team for the IPCC’s AR6 Synthesis Report. Aditi is a human geographer by training and has a PhD from Cambridge University, United Kingdom.',
        'Abstract':'IPCC Working Group II formally launched its report on Impacts, Adaptation and Vulnerability on 28th of February, 2022. The writing of this report involved over 270 scientists who spent last 3 years going through literature and assessing the impact of climate change on human and natural systems, and role of adaptation in alleviating some of these impacts. Water chapter is one among 18 chapters in this report. This chapter reiterates findings from WGI report about intensification of water cycle, and shows how every sector of the economy (agriculture, energy, urban etc.) and ecosystems have been affected by this climate induced intensification of water cycle. Majority of world’s population, especially those involved in climate sensitive occupations like agriculture are feeling impacts of climate change through changes in the water cycle, such as through extreme precipitation, melting of glaciers, floods and droughts. The chapter also finds that water is also a part of solution. A large majority of the adaptation options are in response to water related hazards, or adaptation response itself is water related, e.g., irrigation, soil moisture conservation, water storage, rainwater harvesting etc. Many of these water adaptation responses have several benefits, including instances of climate risk reduction. However, effectiveness of these adaptation measures in reducing climate risks goes down substantially at higher levels of global warming, thereby emphasizing the importance of mitigation along with adaptation.'
      },
      {
        'title':"Progress in developing continental and global scale flood inundation models",
        'Name of the speaker':'Prof. Paul D Bates',
        'Title of the Seminar':'Progress in developing continental and global scale flood inundation models',
        'Date and Time':'02 March 2022 (Wednesday), 4:00pm',
        'Online Platform':'MS Teams [link to  the video of the seminar]',
        'About the Speaker':'Paul Bates FRS is Professor of Hydrology at the University of Bristol, UK and Chairman of Fathom (www.fathom.global). He is one of the world’s leading experts in the modelling of flood inundation with widespread research interests in risk, resilience, uncertainty, governance and decision making in relation to natural hazards and global water issues. His main area of study is to develop new numerical solutions to the Shallow Water equations and combines these with satellite and airborne data to advance our fundamental understanding of flood dynamics and reduce threats to life and economic losses worldwide. Previously, he was Director of the Cabot Institute and Head of the School of Geographical Sciences at Bristol and has spent sabbatical periods at Laboratoire National d’Hydraulique et Environnment in Paris, the EU Joint Research Centre, Princeton University and the NASA Jet Propulsion Lab at CALTECH. He has published over 240 papers in International peer reviewed journals and has an ISI H-Index of 80 and a Google Scholar H-Index of 100. He is a lifetime Fellow of the Royal Society of London and the American Geophysical Union, a Royal Society Wolfson Research Award holder and in 2019 was awarded a CBE by Queen Elizabeth II for services to flood risk management. Through his work with insurers, charities and NGOs the data sets created using methods developed by his team are used to reduce risks to life and economic losses for hundreds of millions of people globally. ',
        'Abstract':'Flooding is one of the most costly natural disasters and every year affects tens of millions of people and causes billions of dollars in losses, and the most damaging events have affect very large areas. Despite this, the reality is that all flood impacts are felt locally and occur at the level of individual properties. The ultimate challenge in flood modelling therefore is how to provide detailed and skilful hazard and risk predictions at the scale of individual buildings over whole continents or even the whole globe. This talk describes recent efforts at the University of Bristol in the UK to build a two dimensional hydrodynamic model at 90m resolution covering the entire planet and 30m over the parts of the US, Europe and the UK, both for current conditions and future climates. The talk describes the technical challenges and also detailed validation studies which demonstrate the strengths and weaknesses of this type of model.'
      },
      {
        'title':"The Anthropocene Concept: Disturbance(s) in the Terrestrial Hydrosphere",
        'Name of the speaker':'Prof. S.K. Tandon',
        'Title of the Seminar':'The Anthropocene Concept: Disturbance(s) in the Terrestrial Hydrosphere',
        'Date and Time':'24 Jan 2022 (Monday), 4:00pm',
        'Online Platform':'MS Teams [link to  the video of the seminar]',
        'About the Speaker':' Prof. S.K. Tandon is an eminent geoscientist and academician who has been associated with several institutions of higher learning of our country. After an early stint at the Wadia Institute of Himalayan Geology from 1971 to 1976, he taught at the University of Delhi for 34 years until his retirement from there in 2010. Later, he was involved in teaching/research and mentoring at the Earth and Environmental Sciences departments of the   IIT Kanpur (2013-2015), IISER Bhopal (2016-2022) and IISER Mohali (2017). Prof. Tandon has broad research interests in the field of geodynamic evolution of India and has contributed significantly to the understanding of several Phanerozoic stratigraphic records of the country, including the Late Quaternary sequences of the Ganga Plains and the Thar desert of Rajasthan. His lasting interest is in the understanding of Earth Surface Processes- both in modern and ancient continental sedimentary systems; it is this interest in Earth Surface Processes that has attracted him to the subject of Anthropocene. Prof. Tandon has authored over 150 research papers and has co-edited both books and journal special issues/volumes. He is a Fellow of all the three science academies in India, besides being a Fellow of the Third World Academy of Sciences. He has served the Research Councils and the Governing Bodies of most of the Earth Sciences institutes of the country, and has chaired several of the Earth Science Committees of the DST, SERB, CSIR, besides having been the Pro-Vice Chancellor of the University of Delhi from 2005 to 2010.',
        'Abstract':'The term Anthropocene, little known two decades ago, was introduced by Crutzen and Stoermer in 2000 and is now in common usage in the discourse of different science disciplines, particularly in the Earth, Environmental and Life Sciences. Further, it has also been adopted in art and cinema, humanities, social sciences, and policy and governance amongst others. The essence of the concept is well articulated in the title of an article published in 2008 by three leading authorities (Steffen, Crutzen, and McNeill): ‘The Anthropocene: Are humans now overwhelming the great forces of nature?’ Notwithstanding debates around the meaning and definition of the term, as well as the placement of the lower boundary of the Anthropocene, the informal usage of the term stands firmly entrenched across several domains of knowledge. Additionally, the concept of a human-dominated planet is closely linked to the ideas of tipping points, planetary boundaries, and the exploration of safe operating space(s) for humanity, that have been quite effectively championed in the last decade by Rockstrom and his collaborators. Of the nine planetary boundaries advanced by these authors in an influential article published in Ecology and Society in 2009, the water boundary along with the attendant water cycle modifications /water resilience are issues of strong concern, and are therefore being elaborated currently. In this talk, I shall discuss the development of these concepts in addition to presenting a few examples from India’s disturbed river systems.'
      }, {
        'title':"Are Cities Culprits or Victims? India’s Carbon Footprint Beyond 2020",
        'Name of the speaker':'Prof. Kala Seetharam Sridhar',
        'Title of the Seminar':'Are Cities Culprits or Victims? India’s Carbon Footprint Beyond 2020',
        'Date and Time':'27 Dec 2021 (Monday), 4:00pm',
        'Online Platform':'MS Teams [link to  the video of the seminar]',
        'About the Speaker':' Kala S Sridhar, Ph D is Professor, Centre for Research in Urban Affairs at the Institute for Social and Economic Change (ISEC), prior to which she was Ford Public Affairs Fellow at Public Affairs Centre, Fellow at the National Institute of Public Finance and Policy and taught at the Indian Institute of Management Lucknow as Assistant and Associate Professor. She has authored or edited several books published by Routledge, Oxford University Press, Palgrave Macmillan, Springer, and Sage, and has published papers in journals which include Regional Science and Urban Economics, Urban Studies, Applied Economics, among others. She is a Fulbright Nehru fellow during 2021-22, hosted by the University of California Los Angeles. She has a Ph.D. from the Ohio State University and M.S. from the University of Iowa. She is a regular contributor of columns to India’s financial dailies such as Economic Times. She has won several international awards for her research on urbanization including the highly competitive Global Development Network medal for outstanding research on development, two times. She was empanelled to be Indian Council for Cultural Relations (ICCR), Chair Professor of Indian Studies (Economics) in Foreign Universities 2015. She is consistently among the top 10% of authors globally on the Social Science Research Network. She has been a member of expert committees on urban development for the Government of Karnataka, and has done extensive research for the Asian Development Bank (ADB). She was member of the Scientific Committee of the 2016 Urban Transitions Conference, co-hosted by Yale University and Elsevier, which was held in Shanghai, People’s Republic of China. She is a referee for many international journals including Urban Studies, Cities, Housing Policy Debate, Environment and Urbanization Asia, among several others. She is on the editorial advisory board of journals such as Area Development and Policy (Taylor Francis), Urban India (published by India’s National Institute of Urban Affairs), and Frontiers in Built Environment Urban Science.',
        'Abstract':' While the Global North and South were very different in terms of their trajectory of economic growth some years ago, now they are increasingly convergent on economic growth as well as their environmental sustainability. It is now also well known that cities are the engines of economic growth in developing countries of the Global South. However, much as they are the engines of the economy, cities are also blamed for carbon emissions due to a number of factors. But cities are also victims of carbon emissions and climate change due to the density of population and economic activity. Carbon emissions are determined not only by urbanization, but also by a city’s spatial area, its income, energy consumption, and value added by industry. In this research we understand the role played by various factors on carbon emissions empirically by examining India’s data at the district level, where city level data on carbon emissions are quite rare. We use a unique dataset of carbon footprint at the district level, adapting from Lee et al (2021). We estimate carbon emissions as dependent on the district area, urbanization, per capita income, literacy rate, workforce participation and population density. We find rising literacy rate, urbanization, labor force participation, poverty ratio and income to be major causes of rising carbon footprint. We find geographic area of a district has no effect on carbon footprint. Given that reducing poverty ratio is a factor in increasing carbon footprint, the question to ask is if this is equitable. The regression is used to predict carbon emissions in the medium term, i.e., 2030, and longer run, i.e., 2050, assuming current trends continue.'
      },
    ],
  },
  {
    'ICWaR Community Seminar Series': [

      {
        'title':"Let us explore the cool sciences",
        'Name of the speaker':'	Maya Suryawanshi R',
        'Title of the Seminar':'Let us explore the cool sciences',
        'Date and Time':' 13 July 2023 (Thursday) at 5 PM',
        'Venue':'ICWaR Seminar Hall',
        'Abstract':'In this seminar, introductory concepts of remote sensing and polar sciences will be discussed. It will start with the familiarization of polar ice features and will continue with the display, processing, and understanding of satellite images for the same features. Also, different physical parameters obtained from satellites will be explained. Furthermore, different scientific activities carried out during the Antarctic expedition will also be discussed. The goal of this seminar is to introduce researchers to the remote sensing of polar regions and make them aware of the Indian Scientific Expedition to Antarctica.'
      },
      {
        'title':"My 69143rd step into the well",
        'Name of the speaker':'Balaram Shaw',
        'Title of the Seminar':'My 69143rd step into the well',
        'Date and Time':'	15 June 2023 (Thursday) at 5 PM',
        'Venue':'ICWaR Seminar Hall',
        'Abstract':'Droughts have far-reaching detrimental impacts on the environment, society, and economy, ranging from regional to national levels. As the drought characteristics are interrelated, multivariate analysis of those is necessary to understand the actual drought situation in a region. However, such studies are limited. Hence, this study aimed to develop a framework to investigate the meteorological and hydrological droughts using a multivariate analysis of drought characteristics in the Pennar River basin (a semi-arid region) of India, dominated by agricultural activity. Long-term observations (1980–2015) of precipitation, temperature, and streamflow were used to calculate the Standardized Precipitation Evapotranspiration Index (SPEI) and Streamflow Drought Index (SDI) at a 3-month timescale. Based on these indices, drought duration, severity, and peak were abstracted using the Run Theory. The best-fit marginal distribution was determined for every drought characteristic to establish the bivariate joint probability distribution (the copula function). Based on the best-fit copula function, the joint probabilities and the joint return periods were estimated. Results revealed that, for meteorological drought, Frank Copula and Survival Clayton copula were the best-fit copula function for the joint risk of drought duration and severity and the combination of drought duration and peak as well as drought severity and peak, respectively. The joint return period of a drought event with characteristics above the 25th percentile of the same varies between 1 and 2 years, whereas it spans between 1 and 45 years for the ­ 50th percentile. This analysis will provide vital information for water management and planning in a region to mitigate droughts.'
      },
      {
        'title':"Quantifying Climate and Catchment Effects on Streamflow using Budyko Framework",
        'Name of the speaker':'Pushkar Sharma',
        'Title of the Seminar':'Quantifying Climate and Catchment Effects on Streamflow using Budyko Framework',
        'Date and Time':'18 May 2023 (Thursday) at 5 PM',
        'Venue':'ICWaR Seminar Hall',
        'Abstract':'Streamflow variability is affected by both climate change and direct human impacts within the catchment. Quantification of the role of these two factors has significant implications for water resources. In recent years, Budyko-based analytical methods have been widely used for such quantification due to their simplicity and efficacy. We present a comparison of such methods to attribute changes in streamflow in four Model Parameter Estimation Experiment (MOPEX) catchments in the contiguous United States. Further, a new, improved Two-stage Decomposition method to separate the role of climate and catchment changes on streamflow is proposed, considering the uncertainty in the catchment parameter that further leads to a range of evaporative index values within a catchment.',
      },
      {
        'title':"Monitoring and management of water pollution",
        'Name of the speaker':'Shairik Sengupta',
        'Title of the Seminar':'Monitoring and management of water pollution',
        'Date and Time':'06 April 2023 (Thursday) at 5 PM',
        'Venue':'ICWaR Seminar Hall',
        'Abstract':'Charcoal-based water filtration is an effective and accessible method for purifying water. This filtration process involves activated charcoal, known for its porous structure and ability to adsorb impurities. This study was carried out with water samples collected from Kolkata and showed the simple yet effective use of charcoal-based filtration of polluted water.',
      },
      {
        'title':"Fate of Carbon Stocks of Indian Vegetation",
        'Name of the speaker':'Abhishek Chakraborty',
        'Title of the Seminar':'Fate of Carbon Stocks of Indian Vegetation',
        'Date and Time':'23 March 2023 (Thursday) at 5 PM',
        'Venue':'ICWaR Seminar Hall',
        'Abstract':' Carbon use efficiency (CUE), defined as the ratio of the net (NPP) to gross primary productivity (GPP), is a valuable metric to examine the extent of atmospheric carbon sequestered by vegetation into biomass. Evaluating CUE is essential for policymakers to devise future carbon sequestration policies and identify hotspots of carbon storage loss. Indian ecosystems face pronounced weather variability across the year. However, the role of weather variability, spatial patterns, temporal dynamics, and resilience to hydroclimatic perturbations of CUE in Indian terrestrial ecosystems remains poorly understood, particularly at sub-annual scales. The lack of sub-annual NPP datasets hinders remote sensing-based sub-annual CUE assessments, but this study derived an 8-day scale NPP dataset through an empirical formulation performed on moderate resolution imaging spectroradiometer (MODIS) products. This study assesses CUE dynamics for India across its six homogeneous meteorological regions (HMRs) and the major biomes of each HMR, including croplands, forests, and grasslands, through a fine-scale remote sensing approach for 2000-2021. The results show pronounced variability of CUE across spatiotemporal scales governed by the water availability-temperature interplay. Distinct patterns were observed among the biomes, depending on the HMRs dictated by the land management practices of the regions. The study also derived sustainability maps of carbon stocks for India from the trend-persistence interplay of CUE, revealing alarming concerns across most HMRs. A severe loss of resilience of carbon stocks was observed, primarily driven by increased precipitation, and warming among meteorological drivers and soil and atmospheric drying among aridity drivers. Overall, this study highlights the critical role of CUE in assessing the carbon sequestration potential of Indian ecosystems and the need for a better understanding of the factors that influence it to develop effective carbon sequestration policies.',
      },
      {
        'title':"River water, seawater, and groundwater interaction in Hooghly River",
        'Name of the speaker':'Biswajit Panda',
        'Title of the Seminar':'River water, seawater, and groundwater interaction in Hooghly River',
        'Date and Time':'23 February 2023 (Thursday) at 5 PM',
        'Venue':'ICWaR Seminar Hall',
        'Abstract':'The rivers of the Himalayas (Ganges-Brahmaputra) bring a significant amount of radiogenic Sr to the oceans. As a result, it is believed that the increase in the ratio of 87Sr to 86Sr in seawater over the past 40 million years is mainly caused by the erosion of the Himalayan region and the subsequent transport of this material by these rivers. Estuaries, which are areas where rivers meet the ocean, play a major role in carrying dissolved and solid materials from the land to the sea. In this study, we present findings on the changes in Sr concentrations and the 87Sr/86Sr ratio in water samples with different levels of saltiness collected from the Hooghly (Ganga) estuary in India, which is dominated by tidal movements.',
      },
      {
        'title':"Study to identify terrestrial Evapotranspiration response to Indian summer monsoon rainfall",
        'Name of the speaker':'Vivek Kumar',
        'Title of the Seminar':'Study to identify terrestrial Evapotranspiration response to Indian summer monsoon rainfall',
        'Date and Time':'	23 August 2022 (Tuesday) at 5 PM',
        'Venue':'ICWaR Seminar Hall',
        'Abstract':' Evapotranspiration (ET) is a process of mass and energy flux. Several different factors influence the ET from vapour pressure gradient, wind shear, temperature, soil type etc. The best description of this process being the Penman-Monteith equation, but it suffers from availability of poor data. This project work investigates the terrestrial ET response to rainfall during Indian summer monsoon comparing between onset & established period and established & withdrawal period using simple defined variables while deliberately ignoring temperature and other factors.',
      },
      {
        'title':"Application of conceptual tank model to Malaprabha catchment using Simulink",
        'Name of the speaker':'Poornima Chandralekha',
        'Title of the Seminar':'Application of conceptual tank model to Malaprabha catchment using Simulink',
        'Date and Time':'11 August 2022 (Thursday) at 5 PM',
        'Venue':'ICWaR Seminar Hall',
        'Abstract':': Rainfall-runoff model using one or more Tanks as a conceptual representation of input-storage-output systems for hydrological processes is extremely popular and has been widely used in significant parts of the world, notably in Asia. The present study is focused on the development and application of the Tank model to the Malaprabha basin, which is in the semi-arid region of Karnataka State, India. The novelty of the present research is that the Tank models were developed using Simulink, an extension of MATLAB is a graphics-based model development environment for system modeling and simulation. In the present analysis, models with 1, 2, and 3 tanks were created and applied to the Malaprabha basin using rainfall and climate data as inputs. Calibration and validation of the models were performed using observed streamflow records at the outlet of the basin. Various statistics such as the Nash-Sutcliffe Efficiency (NSE), the coefficient of determination (R2), root mean square error (RMSE), and percent bias error (PBIAS) were used to evaluate the relative performances of the three model formulations in simulating total runoff at daily, monthly and annual time steps. Sensitivity analysis showed that the maximum contribution to total runoff occurred from the deepest tank, indicating the importance of groundwater contribution to runoff in the Malaprabha basin. The study demonstrates the potential for Simulink to serve as an important tool in the development and application of conceptual hydrological models.',
      },

      {
        'title':"Preliminary studies on developing a sensor for dopamine",
        'Name of the speaker':'Pavithra N',
        'Title of the Seminar':'Preliminary studies on developing a sensor for dopamine',
        'Date and Time':'13 June 2022 (Monday) at 5 PM',
        'Venue':'ICWaR Seminar Hall',
        'Abstract':'Dopamine is a catecholamine that is an essential neurotransmitter in the human body. Thus, even a minute variation in its concentration and metabolism leads to severe neurological damage or diseases such as Parkinson’s, Alzheimer’s, Schizophrenia, and many more. It could be prevented at some scale by early detection. Nanoparticles have a remarkable ability to be used in sensors for detection purposes. This study synthesized copper oxide nanoparticles for dopamine detection, accompanied by the enzyme tyrosinase used as a sensing material. The structural characterization of the nanoparticles and their interaction with dopamine via fluorescence spectroscopy was done to determine the sensitivity. The sensing material showed a selective response to dopamine and no response to interfering analytes like ascorbic acid, cysteine, and tyrosine. The limit of detection (LOD) of dopamine is observed to be 5 µM. This study indicates that sensing material can be a probe for detecting dopamine. This material is further used to develop electrochemical or solid-state sensors.',
      },
      {
        'title':"Assessment of the Seasonal Dynamics and Links with Environmental Change of the Carbon Use Efficiency of Indian Terrestrial Ecosystems",
        'Name of the speaker':'Abishek Chakraborty',
        'Title of the Seminar':'Assessment of the Seasonal Dynamics and Links with Environmental Change of the Carbon Use Efficiency of Indian Terrestrial Ecosystems',
        'Date and Time':'17 May 2022 (Tuesday) at 5 PM',
        'Venue':'ICWaR Seminar Hall',
        'Abstract':'Global vegetation acts as a significant atmospheric carbon sink by converting atmospheric carbon dioxide to biomass. The efficiency of this conversion is termed the vegetation carbon use efficiency (CUE). It quantifies the carbon storage as useful biomass in the vegetation. It is defined as the net to gross primary productivity (NPP/GPP) ratio. CUE assessment is vital for policymakers as it helps plan future carbon sequestration strategies. Earlier studies have depicted the variation of CUE either using process-based models or satellite data for annual temporal scale (Chen and Yu, 2019, Sci Rep; El Masri et al., 2019, Sci Rep). Another study depicted the driving role of climatic factors on the CUE globally (He et al., 2018, Agr Forest Meteorol). However, the impact of meteorological, vegetation, aridity, and anthropogenic factors on the CUE of India’s terrestrial ecosystems at sub-annual (seasonal, sub-seasonal transitional, and monthly) temporal scales is seldom addressed. This study utilizes the Moderate Resolution Imaging Spectroradiometer (MODIS) products of GPP and the net photosynthesis to produce CUE of India’s terrestrial ecosystems at the finer temporal scales (relative to annual scale), i.e., for the four seasons of India (winter, summer, monsoon, post-monsoon), the sub-seasonal transitions (wet and dry season transitions), and the twelve months. We analyze the CUE variation at the spatial scales of the country, homogeneous meteorological regions, provinces, land classes, and the Koppen climate zones from 2000 to 2021. We further discriminate the relative impacts of each environmental driver on the CUE variation of India’s terrestrial ecosystems at these spatial and temporal scales. This study demonstrates the emergent responses of the carbon storage dynamics of Indian terrestrial ecosystems to its environmental drivers and can guide policymakers in ecological restoration.',
      },
      {
        'title':"Increased risk of low water quality, eutrophication, and fish kills under warming in a highly industrialized stretch of the Ganga River ",
        'Name of the speaker':'Sneha Santy',
        'Title of the Seminar':'Increased risk of low water quality, eutrophication, and fish kills under warming in a highly industrialized stretch of the Ganga River',
        'Date and Time':'19 April 2022 (Tuesday) at 5 PM',
        'Venue':'ICWaR Seminar Hall',
        'Abstract':'Extensive industrial pollution, agricultural runoff, and disposal of untreated sewage into the river have made Kanpur the most critical water pollution hotspot of the Ganga River. This study assesses the water quality with climate change for the mid and end of the 21st century and the resulting risk of low water quality, eutrophication, and fish kill in this industrialized stretch passing through Kanpur. For this assessment, climate projections from an ensemble of 20 GCMs for the RCP 4.5 and RCP 8.5 scenarios are used to drive a hydrological model HEC-HMS coupled with the water quality model QUAL2K. The water quality parameters considered are dissolved oxygen, BOD, ammonia, nitrate, total nitrogen, organic, inorganic, total phosphorous, and faecal coliform. The simulation results show water quality degradation in the mid-21st century, improved by the end of the 21st century due to increased streamflow. The risk of eutrophication and fish kill is found to increase with climate change due to the more occurrence of low flow events.',
      },
      {
        'title':"CESM simulation of monsoon low-pressure systems over India and a sensitivity analysis",
        'Name of the speaker':'Tresa Mary Thomas',
        'Title of the Seminar':'CESM simulation of monsoon low-pressure systems over India and a sensitivity analysis',
        'Date and Time':'04 April 2022 (Monday) at 5 PM',
        'Venue':'ICWaR Seminar Hall',
        'Abstract':'Monsoon low-pressure systems (LPS) during the summer monsoon season (June-September) over India are a lifeline for the agriculture-dependent country. We use the Community Earth System Model (CESM1.2.2) to simulate the LPS characteristics (genesis, propagation direction, tracks, intensity, and precipitation) over India and the Bay of Bengal and analyze the influence of Southeast Asian mountains (SAMs) on these characteristics. CESM reproduced most of the LPS characteristics. However, a southward latitudinal shift of about 4° is simulated in the median of the tracks, which is likely due to the weaker simulated upper tropospheric meridional temperature gradient (MTG) in the Indian region. Removal of SAMs is found to have little influence on LPS characteristics. Further, it causes only a slight reduction in mean summer monsoon precipitation (by 5%) and LPS related precipitation (from 10.7±1.0 to 10.3±0.8 mm/day) over India, as SAMs have negligible influence on in-situ westward propagating LPS which are the major contributors to LPS related precipitation. The insensitivity of LPS characteristics and precipitation over India to the removal of SAMs can be attributed to their low height and the insensitivity of MTG to the height of these mountains.',
      },
      {
        'title':"Coupling of hydrological and machine learning models for reservoir storage and inflow forecasting",
        'Name of the speaker':'Mr. Walter Samuel',
        'Title of the Seminar':'Coupling of hydrological and machine learning models for reservoir storage and inflow forecasting',
        'Date and Time':'21 March 2022 (Monday) at 5 PM',
        'Venue':'ICWaR Seminar Hall',
        'Abstract':'Forecasting near real-time water availability in reservoirs helps in effective water resources management, flood control, hydropower generation, irrigation, and drought mitigation. The conceptual framework is built around a deep tech exercise encompassing artificial intelligence, deep-learning, water physics, hydrological science, and geoinformatics, alongside an innovative interdisciplinary approach. The predictive modelling exercise yields meaningful results when it is complemented with human understanding of the physical processes in the river basin. This is achieved by combining machine learning and hydrological modelling. Three deep learning architectures have been used – fully connected deep neural network, long short-term memory network, and WaveNets. They take inputs such as storage, inflow, outflow, and precipitation leading up to the reservoir and use these inputs to predict the inflow and storage level 30, 60 and 90 days ahead. The visualization and dissemination of the results of this exercise and other critical hydro-meteorological datasets are done through an interactive dashboard to help stakeholders make informed decisions.',
      },
      {
        'title':"Numerical Modelling of Ozone Transfer and Microbial Inactivation for Wastewater Treatment",
        'Name of the speaker':'Ms. Reshma Mohan',
        'Title of the Seminar':'Numerical Modelling of Ozone Transfer and Microbial Inactivation for Wastewater Treatment',
        'Date and Time':'31st October 2019 (Thursday) at 4.00 PM',
        'Venue':'ICWaR Seminar Hall',
        'Abstract':'Ozonation is currently considered as one of the most effective microbial disinfection technologies due to its powerful disinfection capacity. The solubility of ozone gas in water is limited, once dissolved, aqueous ozone engages in complex chemistry that includes auto-decomposition reaction with various constituents in water, in addition to reaction with microorganisms. The two widely accepted mechanism of aqueous ozone chemistry include Hoigne, Staeholin and Bader mechanisms and Gordan, Tomiyasn and Fukuton mechanisms. In efforts to meet drinking water regulations and to be cost-effective, it is required to optimize ozone dosage for disinfection. Therefore, there is a need to develop a robust and flexible tool to accurately describe ozone disinfection processes which can aid in design and operation. Computational fluid dynamics (CFD) has come into use recently for evaluating disinfection systems. A multiphase CFD model is developed to analyze the efficiency of ozone disinfection technology used in treatment of greywater in Berambadi primary school located in Berambadi village (rural Karnataka). The mass transfer of ozone species from gas into water is modeled using the Two-Film theory developed by Lewis and Whitman (1924). While the microbial inactivation kinetics by ozone reaction is modeled using the Hom-Haas Model. Transport equations for ozone mass transfer and reactions are incorporated to the multiphase CFD model (with the grey water as the primary phase and ozone as secondary phase). The developed multiphase CFD model is planned to be validated by comparing the numerical and experimental local ozone residual concentrations.',
      },
      {
        'title':"Influence of Irrigation on Soil Carbon Fluxes for a Semi-arid Agro-ecosystem of India",
        'Name of the speaker':'Mr. Abhishek Chakraborty',
        'Title of the Seminar':'Influence of Irrigation on Soil Carbon Fluxes for a Semi-arid Agro-ecosystem of India',
        'Date and Time':'31st July 2019 (Monday) at 4.00 PM',
        'Venue':'ICWaR Seminar Hall',
        'Abstract':'With the increasing population of India, not only is there a growing stress on the water resources of the country but also there is a need to increase the crop yield throughout the nation. Due to these reasons, there is a pressing need to switch to water-saving irrigation practices in the water-stressed climates of semi-arid dryland ecosystems of India. The transformation from flood irrigation to drip and sprinkler irrigation is one such method by which the water- use efficiency of irrigation systems has increased. Also, to cater to the needs of increasing population, there is a requirement to increase the crop yield by either intensifying irrigation or switching to high yielding varieties of crops. These transformations are expected to play a huge part in change in carbon fluxes from soils of these regions. Soil is the largest terrestrial carbon sink and plays an important role in carbon sequestration. Crop production through irrigation and fertilization results in the greenhouse gas emission from the soil to atmosphere. It is expected that a drip or sprinkler irrigation system would have a greater carbon footprint than a conventional flood irrigation system. This is partially attributed to the carbon emission during their manufacturing and partially to the heterogeneous and under saturated state of soil. There is a definite gap in understanding the soil carbon fluxes from the irrigation fields of semi-arid ecosystems in India. In this seminar, I wish to discuss a few methods by which the soil carbon fluxes from a heterogeneous agro-ecosystem of India present in the semi-arid climate can be addressed.',
      },
      {
        'title':"Authigenic clay mineral formation by reverse weathering: Impact on global climate and heavy metal cycling in large water bodies",
        'Name of the speaker':'Mr. Biswajit Panda',
        'Title of the Seminar':'Authigenic clay mineral formation by reverse weathering: Impact on global climate and heavy metal cycling in large water bodies',
        'Date and Time':'7th July 2019 (Monday) at 4.15 PM',
        'Venue':'ICWaR Seminar Hall',
        'Abstract':'Weathering of continental silicate rock consumes  and supply cation to oceans and thereby modulating both climate and sea water chemistry (Raymo et. al., 1988). A series of secondary reactions dominate the transport of these cation from the weathering site to their point of release in oceans. These secondary reactions which lead to the formation of authigenic clay minerals thus acts as a controller of cation flux to the oceans (Misra and Froelich, 2012). The neoformed clays within the fluvial and oceanic system act as a sink for the soluble cation, thus playing a significant role in the global riverine and oceanic elemental budgets. The release of  due to clay mineral formation is in contrast to silicate weathering that acts as a net sink of  and is hence, termed Reverse weathering (Mackenzie and Garrels, 1966). Reverse weathering not only plays a critical role in the geochemical cycling of elements it also modulates the global carbon cycle. In this seminar I am going to discuss some aspects of reverse weathering and the ways to study the same in Indian riverine systems where in recent years heavy metal concentration have been on the rise because of anthropogenic activity.',
      },

      {
        'title':"Physical and Geochemical Characteristics of the Brahmaputra River Basin",
        'Name of the speaker':'Mr. Walter Samuel',
        'Title of the Seminar':'Physical and Geochemical Characteristics of the Brahmaputra River Basin',
        'Date and Time':'9th May 2019 (Thursday) at 4.15 PM',
        'Venue':'ICWaR Seminar Hall',
        'Abstract':'The Brahmaputra River suffers a dramatic change in elevation before it enters India along the eastern syntaxis where it exhumes large amounts of sediments which it eventually deposits along the plains of Assam and Bangladesh. This river system is one of the largest in the world with a high specific discharge and experiences several long-duration floods during monsoon, causing enormous damage to infrastructure, agriculture and livelihood of the inhabitants of low-lying areas in the flood plains. Physical studies carried out on the Brahmaputra river basin have utilised a single hydrological model to simulate the daily discharge. Relying on a single model often leads to predictions that capture some phenomena at the expense of others. Multi-model ensemble hydrological simulation has been an effective method for improving simulation accuracy. Geochemical characteristics related to the major ion chemistry and radioisotope systematics in this river have been previously studied, but none of these studies has focussed on using geochemistry to study flood events that occur annually in the Brahmaputra. The aim is to simultaneously dwell on the physical and geochemical characteristics of the river basin. This enables one to address and investigate questions based on geochemical attributes that may otherwise not be answered using a purely physical modeling approach.',
      },
      {
        'title':"Modelling of Membrane Bioreactors: Hydrodynamic and Biokinetic models",
        'Name of the speaker':'	Ms. Reshma Mohan T.',
        'Title of the Seminar':'Modelling of Membrane Bioreactors: Hydrodynamic and Biokinetic models',
        'Date and Time':'6th March 2019 (Wednesday) at 4.15 PM',
        'Venue':'ICWaR Seminar Hall',
        'Abstract':'The world is currently in a highly water stressed situation, with 844 million people around the globe with no access to clean water. By 2050, it is estimated that 5.7 billion people in the world will have to live in areas  plagued by water scarcity (UN, 2013). The availability of safe drinking water in sufficient quantity is directly linked with how wastewater is managed. In India, about 38671 MLD of untreated sewage is discharged into waterbodies rendering these water sources unfit for use. To prevent contamination of natural water bodies and to achieve water sustainability, there is a need to value wastewater for its potential rather than discard it. Membrane bioreactor (MBR) has emerged as one of the leading technologies for treatment of both municipal and industrial wastewater due to efficiency in producing high quality effluents. There have been several modelling studies focusing on the biological processes and the hydrodynamics aspects of membrane bioreactor. Biokinetic models including the Activated sludge models, Hybrid models and integrated models is used to understand and capture the complexities of the biological processes in MBR. The Hydrodynamic models including Computational Fluid dynamics models (CFD) focus on MBR system design and optimization. A multiphase CFD model is developed to investigate the efficiency of the aeration system in the Membrane Bioreactor. The turbulence in the Bioreactor is modeled using k-є model and the diffusion of oxygen in water from aeration system is modeled using species transport model. The developed CFD model is also validated using existing literature experimental results.',
      },
      {
        'title':"Monsoon low pressure systems and stochastic risk analysis",
        'Name of the speaker':'	Ms. Tresa Mary Thomas',
        'Title of the Seminar':'Monsoon low pressure systems and stochastic risk analysis',
        'Date and Time':'	30th January 2019 (Wednesday) at 4.15 PM',
        'Venue':'ICWaR Seminar Hall',
        'Abstract':'Every year India suffers from floods triggered by Monsoon Low pressure Systems (LPS), which cause disastrous effects at many locations in the country. In the past, a few studies developed procedures for identifying genesis points of LPS and algorithms for tracking their propagation. They were used on various reanalysis products to determine tracks of LPS originating in the Indian subcontinent. But none of those procedures are proven to be effective in predicting the interannual variability of LPS frequency observed by India Meteorological Department (IMD). Questions also arise on the subjectivity involved in the manual procedure (based on pressure charts) considered by IMD for detection of LPS tracks. Inconsistency also exists in future projections of these systems by various studies. Results obtained from investigations performed on different approaches to examine these issues would be presented.',
      },
      {
        'title':"Spatio-temporal variations of runoff and baseflow components using isotopic methods",
        'Name of the speaker':'Mr. Siva Naga Venkat Nara',
        'Title of the Seminar':'Spatio-temporal variations of runoff and baseflow components using isotopic methods',
        'Date and Time':'	28th  November 2018 (Wednesday) at 4.00 PM',
        'Venue':'ICWaR Seminar Hall',
        'Abstract':'The quantification of runoff and base flow components of hydrograph in terms of water fluxes and chemical composition is an important issue in catchment hydrology. Particularly in a riverine system contribution of hydrograph components depends on the initial state of the various hydrological reservoirs and on the characteristics of the hydrological input (precipitation). Baseflow reacts slowly to precipitation and is usually associated with water discharged from groundwater storage. By separating the baseflow (pre-event water) from the stream discharge the contribution of surface and groundwater can be quantified using stable isotope tracers. The stable isotopes of water namely 18O and 2H, which are part of the water molecule, are typically considered in the hydrological investigations owing to their spatio-temporal variations resulting from isotope fractionations along different phase changes of water cycle and diffusion. Various atmospheric processes such as advection, condensation and evaporation directly impact the composition of stable water isotope, which consequently influence the groundwater isotopic composition. As a part of the Isotope Hydrograph Separations (IHS), study has been done for Kabini catchment by applying end member mixing analysis (EMMA) to quantify the pre-event water and event water.',
      },
      {
        'title':"Impact of Climate change on Water quality for Ganga river",
        'Name of the speaker':'	Ms. Sneha Santy',
        'Title of the Seminar':'Impact of Climate change on Water quality for Ganga river',
        'Date and Time':'	31st   October 2018 (Wednesday) at 4.00 PM',
        'Venue':'ICWaR Seminar Hall',
        'Abstract':'Climate change will have significant effects on fresh water quality due to increase in river temperature and changes in magnitude of stream flow. Other major factors affecting water quality are the point and non-point sources of pollution which include industrial & municipal sewage discharge and agricultural runoff. Due to climate change, there can be deterioration of water quality even if the effluent discharged is within permissible limits. Objective of the study is to quantify the response of water quality due to climate change, and to identify hotspots of pollution in the Ganga River. Water quality analysis is carried out using a water quality model QUAL2K. The impact of climate change is assessed using 2 methods: hypothetical scenarios of temperature & stream flow and temperature outputs of GCMs for various RCP scenarios as input to water quality model.',
      },
    ],
  }

]
